### ISSUE TITLE
Preprocessor directive issue

### ISSUE THREAD

**Issue by borislav968** [Ro5bert/avra#11] opened 2020-03-19 08:32 UTC
The #define directive causes error if the value is in quotes. This should make PLATFORM_CODE take one of the predefined values (the code works well with avrasm):

`
#if defined(_PLATFORM_M64_)
.INCLUDE "m64def.inc"
#message "ATMega64 platform used"
#define PLATFORM_CODE "64  "

#elif defined(_PLATFORM_M644_)
.INCLUDE "m644def.inc"
#message "ATMega644 platform used"
#define PLATFORM_CODE "644 "
.equ    SPMCR  = SPMCSR
.equ    WDTCR  = WDTCSR
.equ    EEWE   = EEPE
.equ    EEMWE  = EEMPE

#elif defined(_PLATFORM_M1284_)
.INCLUDE "m1284def.inc"
#message "ATMega1284 platform used"
#define PLATFORM_CODE "1284"
.equ    SPMCR  = SPMCSR
.equ    WDTCR  = WDTCSR
.equ    EEWE   = EEPE
.equ    EEMWE  = EEMPE

#else
 #error "Wrong platform identifier!"
#endif
`

...used in

`
; MCU type information string, size must be 4 bytes
                  .db PLATFORM_CODE
`

But executing causes the error:

`Pass 1...
seculdr.asm(98) : Error   : Found no label/variable/constant named`

String 98 is:
`#define PLATFORM_CODE "644 "`

Using the values without quotes doesn't cause any errors, but passing the value without quotes (with spaces at the end) makes the code less obvious.

**Comment by Ro5bert** [comment] 2020-04-19 18:32
Hi. Thanks for the issue and sorry it took so long for me to get to this. It looks like the problem is that AVRA does not support defining strings like AVRASM; only numeric constants are allowed. The reason you get the error message "Found no label/variable/constant named" is just because AVRA defaults to parsing expressions as a label/variable/constant name if it cannot parse it as anything else (i.e., parsing it as a label/variable/constant name is the last thing it tries, so that's the error message you get when it fails).

Keep in mind that AVRA's `#define` (which is equivalent to `.define`) is not the same as AVRASM's, which is modelled closely after the C preprocessor's `#define`. As stated [here](https://github.com/Ro5bert/avra/blob/master/USAGE.md#directive-define), `.define`/`#define` in AVRA is really just the same thing as `.equ`. Hence, I'm not sure if it makes sense to extend the current functionality to support strings. If we did, I think the only place string constants could be used is in `.db`.

It could be argued that all the directives starting with `#` in AVRA should behave like their counterparts in AVRASM (i.e., they should be *preprocessor* directives, and not simply an alias for assembler directives starting with `.`), but I imagine some people have already relied on it working the way it currently does.

I'm closing this issue for now, but feel free to comment with your thoughts.

**Closed by Ro5bert** 2020-04-19 18:32 UTC
